services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nelson-johns-portfolio
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - web-network
      - turbolessons_cloud_service_net
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  web-network:
    driver: bridge
  turbolessons_cloud_service_net:
    external: true
