services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nelson-johns-portfolio
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - web-network
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  web-network:
    driver: bridge
